name: Upstream Sync&ReplaceIP

permissions:
    contents: write

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    sync_with_upstream:
        name: Sync with Upstream
        runs-on: ubuntu-latest
        if: ${{ github.event.repository.fork }}

        steps:
            - name: Checkout target repo
              uses: actions/checkout@v3

            - name: Sync Upstream
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                  upstream_sync_repo: qwerttvv/Beijing-IPTV
                  upstream_sync_branch: master
                  target_sync_branch: master
                  test_mode: false

            - name: Check for Failure
              if: failure()
              run: |
                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
                  exit 1
    
    replace_ip:
        name: Replace IP to your own
        runs-on: ubuntu-latest
        steps:
             - name: Replace IP
               uses: datamonsters/replace-action
               with:
                  files: '/uses: datamonsters/replace-action
with:
  files: 'path1/file1,path2/file2'
  replacements: 'foo=bar,$FOO=Bar_Value'
                  replacements: 'foo=bar,$FOO=Bar_Value
